apiVersion: v1
kind: Service
metadata:
  name: homepage
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.103
  labels:
    app: homepage
spec:
  type: LoadBalancer
  selector:
    app: homepage
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 3000
      port: 80
