configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    users.anonymous.enabled: "false"

crds:
  install: true
  keep:  false

global:
  revisionHistoryLimit: 3

applicationSet:
  metrics:
    enabled: true
  replicas: 2

controller:
  metrics:
    enabled: true

dex:
  metrics:
    enabled: true

notifications:
  metrics:
    enabled: true

redis-ha:
  enabled: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
  service:
    annotations:
      io.cilium/lb-ipam-ips: 10.10.10.102
    type: LoadBalancer
