apiVersion: v1
kind: Service
metadata:
  name: tautulli
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.131
  labels:
    app: tautulli
spec:
  type: LoadBalancer
  selector:
    app: tautulli
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 8181
      port: 80
