apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
spec:
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
        - name: tautulli
          image: tautulli/tautulli
          envFrom:
            - configMapRef:
                name: tautulli-env-vars
          ports:
            - name: "http"
              containerPort: 8181
              protocol: TCP
          volumeMounts:
            - name: tautulli-data
              mountPath: /config
      volumes:
        - name: tautulli-data
          persistentVolumeClaim:
            claimName: tautulli-data
