# https://gethomepage.dev/latest/widgets/info/datetime/

- datetime:
    text_size: xl
    format:
      timeStyle: medium

- greeting:
    text_size: xl
    text: home.mezmer.ch

- openmeteo:
    latitude: 46.20222
    longitude: 6.14569
    units: metric
    cache: 5

- kubernetes:
    cluster:
      show: false
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
