apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Ti
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      cache: writethrough
      ssd: "true"
      storage: data
      storage.kubernetes.io/csiProvisionerIdentity: 1697594800660-2288-csi.proxmox.sinextra.dev
    volumeHandle: homelab/proxmox/data/vm-9999-Nextcloud-Data
  mountOptions:
    - noatime
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
            - homelab
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - proxmox
  storageClassName: data
