apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1.5Ti
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      cache: writethrough
      ssd: "true"
      storage: data
      storage.kubernetes.io/csiProvisionerIdentity: 1697594800660-2288-csi.proxmox.sinextra.dev
    volumeHandle: homelab/proxmox/data/vm-4061-disk-3
  mountOptions:
    - noatime
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
            - homelab
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - proxmox
  storageClassName: data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      cache: writethrough
      ssd: "true"
      storage: data
      storage.kubernetes.io/csiProvisionerIdentity: 1697594800660-2288-csi.proxmox.sinextra.dev
    volumeHandle: homelab/proxmox/data/vm-4061-disk-4
  mountOptions:
    - noatime
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
            - homelab
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - proxmox
  storageClassName: data
