apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.104
  labels:
    app: nextcloud
spec:
  type: LoadBalancer
  selector:
    app: nextcloud
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 3000
      port: 80
