apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: data 
  volumeName: rutorrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-fileserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: nfs-client 
  volumeName: rutorrent-fileserver
