apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.106
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 8989
      port: 80
