apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.107
  labels:
    app: radarr
spec:
  type: LoadBalancer
  selector:
    app: radarr
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 7878
      port: 80
