apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.109
  labels:
    app: prowlarr
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 9696
      port: 80
