apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr
          envFrom:
            - configMapRef:
                name: prowlarr-env-vars
          ports:
            - name: "http"
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
      volumes:
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data
  
