apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: data
  volumeName: bazarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
  volumeName: bazarr-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-subs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
  volumeName: bazarr-subs
