apiVersion: v1
kind: Service
metadata:
  name: bazarr
  annotations:
    io.cilium/lb-ipam-ips: 10.10.10.108
  labels:
    app: bazarr
spec:
  type: LoadBalancer
  selector:
    app: bazarr
  ports:
    - name: "http"
      protocol: TCP
      targetPort: 6767 
      port: 80
